
development:
  adapter: postgresql
  encoding: unicode
  database: dbc92tj79uqust
  user: umdwwxjfnnnfkc
  password: i0MqOWTSuWFDbYDAKfPWxUFYrS
  host: ec2-54-225-117-56.compute-1.amazonaws.com
  



